-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 21:20:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `projeto_integrador` ;

-- -----------------------------------------------------
-- Table `projeto_integrador`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Aluno` (
  `CPF` VARCHAR(11) NOT NULL,
  `altura` FLOAT NULL,
  `peso` FLOAT NULL,
  UNIQUE INDEX `CPFAluno_UNIQUE` (`CPF` ASC),
  CONSTRAINT `fk_aluno_cpf`
    FOREIGN KEY (`CPF`)
    REFERENCES `projeto_integrador`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `projeto_integrador`.`CEP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`CEP` (
  `CEP` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Cidade` (
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Contato` (
  `CPF` VARCHAR(11) NULL,
  `fixo` VARCHAR(11) NULL,
  `movel` VARCHAR(11) NULL,
  `email` VARCHAR(11) NULL,
  CONSTRAINT `fk_contato_pessoa`
    FOREIGN KEY (`CPF`)
    REFERENCES `projeto_integrador`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Endereco` (
  `CPF` VARCHAR(11) NULL,
  `logradouro` VARCHAR(20) NULL,
  `via` VARCHAR(50) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(10) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(2) NULL,
  `CEP` VARCHAR(8) NULL,
  INDEX `fk_endereco_pessoa_idx` (`CPF` ASC) VISIBLE,
  INDEX `fk_endereco_logradouro_idx` (`logradouro` ASC) VISIBLE,
  INDEX `fk_endereco_via_idx` (`via` ASC) VISIBLE,
  INDEX `fk_endereco_cidade_idx` (`cidade` ASC) VISIBLE,
  INDEX `fk_endereco_estado_idx` (`estado` ASC) VISIBLE,
  INDEX `fk_endereco_cep_idx` (`CEP` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoa`
    FOREIGN KEY (`CPF`)
    REFERENCES `projeto_integrador`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_endereco_logradouro`
    FOREIGN KEY (`logradouro`)
    REFERENCES `projeto_integrador`.`Logradouro` (`logradouro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_endereco_via`
    FOREIGN KEY (`via`)
    REFERENCES `projeto_integrador`.`Via` (`via`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_endereco_cidade`
    FOREIGN KEY (`cidade`)
    REFERENCES `projeto_integrador`.`Cidade` (`Cidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_endereco_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `projeto_integrador`.`Estado` (`estado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_endereco_cep`
    FOREIGN KEY (`CEP`)
    REFERENCES `projeto_integrador`.`CEP` (`CEP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Estado` (
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Exercicio` (
  `Exercicio` VARCHAR(45) NOT NULL,
  `Serie` VARCHAR(1) NOT NULL,
  `Repeticao` VARCHAR(45) NOT NULL,
  `Carga` VARCHAR(45) NOT NULL,
  `Treino` VARCHAR(1) NOT NULL,
  INDEX `fk_treino_musculacao_idx` (`Treino` ASC) VISIBLE,
  CONSTRAINT `fk_treino_musculacao`
    FOREIGN KEY (`Treino`)
    REFERENCES `projeto_integrador`.`Musculacao` (`Treino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Funcionario` (
  `CPF` VARCHAR(11) NOT NULL,
  `escolaridade` VARCHAR(45) NULL,
  `CTPS` VARCHAR(20) NULL,
  UNIQUE INDEX `CPFFuncionario_UNIQUE` (`CPF` ASC),
  CONSTRAINT `fk_funcionario_pessoa`
    FOREIGN KEY (`CPF`)
    REFERENCES `projeto_integrador`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Login` (
  `usuario` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `CPFAluno` VARCHAR(11) NULL,
  `CPFFuncionario` VARCHAR(11) NULL,
  INDEX `fk_login_aluno_idx` (`CPFAluno` ASC) VISIBLE,
  INDEX `fk_login_funcionario_idx` (`CPFFuncionario` ASC) VISIBLE,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_login_aluno`
    FOREIGN KEY (`CPFAluno`)
    REFERENCES `projeto_integrador`.`Aluno` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_login_funcionario`
    FOREIGN KEY (`CPFFuncionario`)
    REFERENCES `projeto_integrador`.`Funcionario` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Logradouro` (
  `logradouro` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`logradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Modalidade` (
  `idModalidade` VARCHAR(50) NOT NULL,
  `semana` CHAR(7) NULL,
  `minimoParticipantes` INT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Musculacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Musculacao` (
  `Treino` VARCHAR(1) NOT NULL,
  `Objetivo` VARCHAR(45) NOT NULL,
  `Sessao` INT(3) NOT NULL,
  `Observacao` VARCHAR(45) NULL,
  `CPFAluno` VARCHAR(11) NOT NULL,
  INDEX `fk_musculacao_pessoa_idx` (`CPFAluno` ASC) VISIBLE,
  PRIMARY KEY (`Treino`),
  CONSTRAINT `fk_musculacao_pessoa`
    FOREIGN KEY (`CPFAluno`)
    REFERENCES `projeto_integrador`.`Pessoa` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Participantes` (
  `idTurma` INT NULL,
  `CPFAluno` VARCHAR(11) NULL,
  `CPFFuncionario` VARCHAR(11) NULL,
  INDEX `fk_cpf_aluno_idx` (`CPFAluno` ASC) VISIBLE,
  INDEX `fk_cpf_funcionario_idx` (`CPFFuncionario` ASC) VISIBLE,
  INDEX `fk_participantes_turma_idx` (`idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_cpf_aluno`
    FOREIGN KEY (`CPFAluno`)
    REFERENCES `projeto_integrador`.`Aluno` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cpf_funcionario`
    FOREIGN KEY (`CPFFuncionario`)
    REFERENCES `projeto_integrador`.`Funcionario` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_participantes_turma`
    FOREIGN KEY (`idTurma`)
    REFERENCES `projeto_integrador`.`Turma` (`idTurma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Pessoa` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `sexo` TINYINT(1) NULL,
  `dataNascimento` DATE NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Turma` (
  `idTurma` INT NOT NULL,
  `idModalidade` VARCHAR(50) NULL,
  `horarioInicio` TIME NULL,
  `duracao` FLOAT NULL,
  PRIMARY KEY (`idTurma`),
  INDEX `fk_turma_modalidade_idx` (`idModalidade` ASC) VISIBLE,
  CONSTRAINT `fk_turma_modalidade`
    FOREIGN KEY (`idModalidade`)
    REFERENCES `projeto_integrador`.`Modalidade` (`idModalidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`Via`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`Via` (
  `via` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`via`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
